package com.demo.common.model;

import com.demo.common.model.base.BaseApplyRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ApplyRecords extends BaseApplyRecords<ApplyRecords> {
	public static final ApplyRecords dao = new ApplyRecords();
}
