package com.demo.common.model;

import com.demo.common.model.base.BaseRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Records extends BaseRecords<Records> {
	public static final Records dao = new Records();
}
