package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsers<M extends BaseUsers<M>> extends Model<M> implements IBean {

	public void setFid(Integer fid) {
		set("fid", fid);
	}

	public Integer getFid() {
		return get("fid");
	}

	public void setFuserName(String fuserName) {
		set("fuser_name", fuserName);
	}

	public String getFuserName() {
		return get("fuser_name");
	}

	public void setFpassWord(String fpassWord) {
		set("fpass_word", fpassWord);
	}

	public String getFpassWord() {
		return get("fpass_word");
	}

	public void setFrole(String frole) {
		set("frole", frole);
	}

	public String getFrole() {
		return get("frole");
	}

	public void setFcreateTime(java.util.Date fcreateTime) {
		set("fcreate_time", fcreateTime);
	}

	public java.util.Date getFcreateTime() {
		return get("fcreate_time");
	}

	public void setFstate(Integer fstate) {
		set("fstate", fstate);
	}

	public Integer getFstate() {
		return get("fstate");
	}

}
