package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApplyRecords<M extends BaseApplyRecords<M>> extends Model<M> implements IBean {

	public void setFid(Integer fid) {
		set("fid", fid);
	}

	public Integer getFid() {
		return get("fid");
	}

	public void setFcreatTime(String fcreatTime) {
		set("fcreat_time", fcreatTime);
	}

	public String getFcreatTime() {
		return get("fcreat_time");
	}

	public void setFdesc(String fdesc) {
		set("fdesc", fdesc);
	}

	public String getFdesc() {
		return get("fdesc");
	}

	public void setFreason(String freason) {
		set("freason", freason);
	}

	public String getFreason() {
		return get("freason");
	}

	public void setFapplyer(String fapplyer) {
		set("fapplyer", fapplyer);
	}

	public String getFapplyer() {
		return get("fapplyer");
	}

	public void setFchecker(String fchecker) {
		set("fchecker", fchecker);
	}

	public String getFchecker() {
		return get("fchecker");
	}

	public void setFstate(Integer fstate) {
		set("fstate", fstate);
	}

	public Integer getFstate() {
		return get("fstate");
	}

}
