package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setFid(Integer fid) {
		set("fid", fid);
	}

	public Integer getFid() {
		return get("fid");
	}

	public void setFcode(String fcode) {
		set("fcode", fcode);
	}

	public String getFcode() {
		return get("fcode");
	}

	public void setFname(String fname) {
		set("fname", fname);
	}

	public String getFname() {
		return get("fname");
	}

	public void setFuser(String fuser) {
		set("fuser", fuser);
	}

	public String getFuser() {
		return get("fuser");
	}

	public void setFtype(Integer ftype) {
		set("ftype", ftype);
	}

	public Integer getFtype() {
		return get("ftype");
	}

	public void setFprice(Double fprice) {
		set("fprice", fprice);
	}

	public Double getFprice() {
		return get("fprice");
	}

	public void setFstate(Integer fstate) {
		set("fstate", fstate);
	}

	public Integer getFstate() {
		return get("fstate");
	}

	public void setFcreateTime(java.util.Date fcreateTime) {
		set("fcreate_time", fcreateTime);
	}

	public java.util.Date getFcreateTime() {
		return get("fcreate_time");
	}

}
